[pytest]
testpaths=tests
pythonpath = .
env_override_existing_values = 1
env_files =
    .test.env
markers =
    positive: mark a test as a positive test
    negative: mark a test as a negative test
    slow: mark slow tests
    agent: mark agent tests