"""migrate timezone

Revision ID: 0344fdc6be60
Revises: d310f79a43ef
Create Date: 2026-02-15 17:44:11.839926

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context

# revision identifiers, used by Alembic.
revision: str = "0344fdc6be60"
down_revision: Union[str, Sequence[str], None] = "d310f79a43ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "timezones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("ian", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ian"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "users", sa.Column("location", sa.String(), server_default="", nullable=True)
    )
    op.add_column("users", sa.Column("timezone_id", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("users_city_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "timezones", ["timezone_id"], ["id"])
    op.drop_column("users", "city_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("city_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_city_id_fkey"),
        "users",
        "cities",
        ["city_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("users", "timezone_id")
    op.drop_column("users", "location")
    op.drop_table("timezones")
    # ### end Alembic commands ###
