"""migragrate db

Revision ID: 048910357d06
Revises: 0344fdc6be60
Create Date: 2026-02-25 21:28:51.589906

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

# revision identifiers, used by Alembic.
revision: str = "048910357d06"
down_revision: Union[str, Sequence[str], None] = "0344fdc6be60"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cities")
    op.alter_column(
        "user_telegram",
        "telegram_id",
        existing_type=sa.INTEGER(),
        type_=sa.BigInteger(),
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "UNCOMPLETED",
        "CANCELED_BY_INITIATOR",
        "CANCELED_BY_TARGET",
        "COMPLETED",
        "SKIPPED",
        "ONGOING",
        name="matchstatus",
    ).create(op.get_bind())
    op.alter_column(
        "user_telegram",
        "telegram_id",
        existing_type=sa.BigInteger(),
        type_=sa.INTEGER(),
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column(
        "matches",
        "status",
        existing_type=sa.Enum(
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
            "ONGOING",
            name="meetstatus",
        ),
        type_=postgresql.ENUM(
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
            "ONGOING",
            name="matchstatus",
        ),
        existing_nullable=True,
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "country", sa.VARCHAR(length=128), autoincrement=False, nullable=True
        ),
        sa.Column("city", sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            "timezone",
            sa.VARCHAR(length=256),
            server_default=sa.text("'UTC'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("cities_pkey")),
    )
    sa.Enum(
        "UNCOMPLETED",
        "CANCELED_BY_INITIATOR",
        "CANCELED_BY_TARGET",
        "COMPLETED",
        "SKIPPED",
        "ONGOING",
        name="meetstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
