"""add it experience

Revision ID: 1e97aaa2fb0f
Revises: 80ac45a9f45e
Create Date: 2026-03-06 15:22:05.888579

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context

# revision identifiers, used by Alembic.
revision: str = "1e97aaa2fb0f"
down_revision: Union[str, Sequence[str], None] = "80ac45a9f45e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("experience", sa.String(length=256), nullable=True)
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "experience")
    # ### end Alembic commands ###
