"""add time quant info

Revision ID: 1f8e1832b25d
Revises: 23882a0c99f0
Create Date: 2026-01-29 09:38:14.607419

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "1f8e1832b25d"
down_revision: Union[str, Sequence[str], None] = "23882a0c99f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("quant_id", sa.SmallInteger(), nullable=False))
    op.create_foreign_key(
        None, "matches", "time_quants", ["quant_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.drop_column("matches", "quant_id")
    # ### end Alembic commands ###
