"""add users enums possibilities

Revision ID: 22996e9d8adb
Revises: a6067ac7d25d
Create Date: 2025-12-28 16:18:57.092674

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import context, op
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "22996e9d8adb"
down_revision: Union[str, Sequence[str], None] = "a6067ac7d25d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            "ALTER TABLE matches ALTER COLUMN status TYPE matchstatus USING status::matchstatus"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "matches",
        "status",
        existing_type=sa.Enum(
            "FOLLOWING",
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
            name="matchstatus",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
