"""enrich via user embedding

Revision ID: 23882a0c99f0
Revises: c5ef317e2938
Create Date: 2026-01-26 17:14:48.986867

"""

from typing import Sequence, Union

import pgvector
from alembic import op
import os
import sqlalchemy as sa

from alembic import context
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "23882a0c99f0"
down_revision: Union[str, Sequence[str], None] = "c5ef317e2938"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_embeddings",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("primary_focus", sa.String(), nullable=False),
        sa.Column("archetype", sa.String(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_index(
        "user_embedding_index",
        "user_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.sync_enum_values(
        "public",
        "matchstatus",
        [
            "FOLLOWING",
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
            "ONGOING",
        ],
        [("matches", "status")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "matchstatus",
        [
            "FOLLOWING",
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
        ],
        [("matches", "status")],
        enum_values_to_rename=[],
    )
    op.drop_index(
        "user_embedding_index",
        table_name="user_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64, "dim": 768},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.drop_table("user_embeddings")
    # ### end Alembic commands ###
