"""enrich_user_data

Revision ID: 2ad981a1955c
Revises: 75b8cecb7568
Create Date: 2026-01-15 15:57:16.538629

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "2ad981a1955c"
down_revision: Union[str, Sequence[str], None] = "75b8cecb7568"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("is_active", sa.Boolean(), server_default="True", nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "use_telegram_channel", sa.Boolean(), server_default="True", nullable=False
        ),
        sa.Column(
            "use_email_channel", sa.Boolean(), server_default="True", nullable=False
        ),
        sa.Column(
            "count_meets_in_week", sa.Integer(), server_default="2", nullable=False
        ),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.add_column(
        "match_requests", sa.Column("initiator_user_id", sa.UUID(), nullable=True)
    )
    op.drop_constraint(
        op.f("match_requests_user_id_fkey"), "match_requests", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "match_requests", "users", ["initiator_user_id"], ["id"]
    )
    op.drop_column("match_requests", "user_id")
    op.add_column("matches", sa.Column("initiator_user_id", sa.UUID(), nullable=True))
    op.drop_constraint(op.f("unique_user_target_date"), "matches", type_="unique")
    op.create_unique_constraint(
        "unique_user_target_date",
        "matches",
        ["initiator_user_id", "target_user_id", "date_at"],
    )
    op.drop_constraint(op.f("matches_user_id_fkey"), "matches", type_="foreignkey")
    op.create_foreign_key(
        None, "matches", "users", ["initiator_user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("matches", "user_id")
    op.add_column("users", sa.Column("education", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("workplace", sa.String(length=256), nullable=True))
    op.add_column("users", sa.Column("birthday", sa.Date(), nullable=True))
    op.drop_column("users", "is_active")
    op.drop_column("users", "count_meets_in_week")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "count_meets_in_week",
            sa.INTEGER(),
            server_default=sa.text("2"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("users", "birthday")
    op.drop_column("users", "workplace")
    op.drop_column("users", "education")
    op.add_column(
        "matches", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "matches", type_="foreignkey")
    op.create_foreign_key(
        op.f("matches_user_id_fkey"),
        "matches",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("unique_user_target_date", "matches", type_="unique")
    op.create_unique_constraint(
        op.f("unique_user_target_date"),
        "matches",
        ["user_id", "target_user_id", "date_at"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("matches", "initiator_user_id")
    op.add_column(
        "match_requests",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "match_requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("match_requests_user_id_fkey"),
        "match_requests",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_column("match_requests", "initiator_user_id")
    op.drop_table("user_settings")
    # ### end Alembic commands ###
