"""fix it expierence column type

Revision ID: 368d5622fc6e
Revises: 1e97aaa2fb0f
Create Date: 2026-03-06 16:03:51.953056

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context

# revision identifiers, used by Alembic.
revision: str = "368d5622fc6e"
down_revision: Union[str, Sequence[str], None] = "1e97aaa2fb0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("expierence", sa.SmallInteger(), nullable=True))
    op.drop_column("users", "experience")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "experience", sa.VARCHAR(length=256), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("users", "expierence")
    # ### end Alembic commands ###
