"""update user category

Revision ID: 805e2d43d535
Revises: a5fe35cda91b
Create Date: 2025-12-23 10:02:12.702660

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import context, op
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "805e2d43d535"
down_revision: Union[str, Sequence[str], None] = "a5fe35cda91b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skills",
        "weight",
        existing_type=sa.SMALLINT(),
        type_=sa.Float(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::smallint"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "skills",
        "weight",
        existing_type=sa.Float(),
        type_=sa.SMALLINT(),
        existing_nullable=False,
        existing_server_default=sa.text("'0'::smallint"),
    )
    op.drop_column("categories", "weight")
    # ### end Alembic commands ###
