"""add feedback

Revision ID: 80ac45a9f45e
Revises: d5a97e9137bf
Create Date: 2026-03-04 11:00:32.092696

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

# revision identifiers, used by Alembic.
revision: str = "80ac45a9f45e"
down_revision: Union[str, Sequence[str], None] = "d5a97e9137bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("match_criterias", sa.Column("user_id", sa.UUID(), nullable=False))
    op.add_column(
        "match_criterias",
        sa.Column("mentor_role", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.add_column(
        "match_criterias",
        sa.Column("mentee_role", postgresql.ARRAY(sa.String()), nullable=True),
    )
    op.create_foreign_key(None, "match_criterias", "users", ["user_id"], ["id"])
    op.drop_column("match_criterias", "target_ids")
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match_criterias",
        sa.Column(
            "target_ids",
            postgresql.ARRAY(sa.UUID()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "match_criterias", type_="foreignkey")
    op.drop_column("match_criterias", "mentee_role")
    op.drop_column("match_criterias", "mentor_role")
    op.drop_column("match_criterias", "user_id")
    # ### end Alembic commands ###
