"""allow_duplicate_user_contacts

Revision ID: 85ae63976f0c
Revises: 2ad981a1955c
Create Date: 2026-01-16 16:59:25.349079

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "85ae63976f0c"
down_revision: Union[str, Sequence[str], None] = "2ad981a1955c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_contact_value"), "user_contacts", type_="unique")
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_contact_value"),
        "user_contacts",
        ["value"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
