"""Initial create table

Revision ID: a5fe35cda91b
Revises:
Create Date: 2025-12-21 14:26:53.495511

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import text

from alembic import context, op

# revision identifiers, used by Alembic.
revision: str = "a5fe35cda91b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    recreate_schema()
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("country", sa.String(length=128), nullable=True),
        sa.Column("city", sa.String(length=256), nullable=False),
        sa.Column(
            "timezone", sa.String(length=256), server_default="UTC", nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "goals",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "time_quants",
        sa.Column("id", sa.SmallInteger(), nullable=False),
        sa.Column("hour", sa.SmallInteger(), nullable=False),
        sa.Column("day", sa.SmallInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "skills",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("weight", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("bio", sa.String(length=512), nullable=True),
        sa.Column("rating", sa.SmallInteger(), server_default="0", nullable=True),
        sa.Column("city_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "matches",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "date_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["target_user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "target_user_id", "date_at", name="unique_user_target_date"
        ),
    )
    op.create_table(
        "user_contacts",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.Column("contact_type", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "contact_type"),
        sa.UniqueConstraint("value", name="uq_contact_value"),
    )
    op.create_table(
        "user_goals",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("goal_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["goal_id"], ["goals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "goal_id"),
    )
    op.create_table(
        "user_mentee_skills",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "skill_id"),
    )
    op.create_table(
        "user_mentor_skills",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "skill_id"),
    )
    op.create_table(
        "user_photos",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("photo_type", sa.String(length=10), nullable=True),
        sa.Column("photo_url", sa.String(length=256), nullable=True),
        sa.Column("photo_s3_key", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "photo_type", name="uq_user_photo_type"),
    )
    op.create_table(
        "user_quants",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("quant_id", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(["quant_id"], ["time_quants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "quant_id"),
    )
    op.create_table(
        "user_skills",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["skill_id"], ["skills.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "skill_id"),
    )
    op.create_table(
        "user_telegram",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("telegram_id", sa.Integer(), nullable=False),
        sa.Column("telegram_username", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("telegram_id"),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    recreate_schema()
    # ### end Alembic commands ###


def recreate_schema():
    op.execute(
        text(
            """

    drop table if exists matches cascade;

    drop type if exists matchstatus cascade;

    drop table if exists user_contacts cascade;

    drop table if exists user_goals cascade;

    drop table if exists goals cascade;

    drop table if exists user_mentee_skills cascade;

    drop table if exists user_mentor_skills cascade;

    drop table if exists user_photos cascade;

    drop table if exists user_quants cascade;

    drop table if exists time_quants cascade;

    drop table if exists user_skills cascade;

    drop table if exists skills cascade;

    drop table if exists categories cascade;

    drop table if exists user_telegram cascade;

    drop table if exists match_requests cascade;

    drop type if exists matchrequeststatus cascade;

    drop table if exists possible_matches cascade;

    drop type if exists possiblematchstatus cascade;

    drop table if exists users cascade;

    drop table if exists cities cascade;

                    """
        )
    )
