"""add users manual search possibilities

Revision ID: a6067ac7d25d
Revises: 805e2d43d535
Create Date: 2025-12-28 16:14:33.797396

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import context, op
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "a6067ac7d25d"
down_revision: Union[str, Sequence[str], None] = "805e2d43d535"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "FOLLOWING",
        "UNCOMPLETED",
        "CANCELED_BY_INITIATOR",
        "CANCELED_BY_TARGET",
        "COMPLETED",
        "SKIPPED",
        name="matchstatus",
    ).create(op.get_bind())
    sa.Enum("PENDING", "APPROVED", "REJECTED", name="matchrequeststatus").create(
        op.get_bind()
    )
    sa.Enum("CURRENT", "LAST", "NEXT", name="possiblematchstatus").create(op.get_bind())
    op.create_table(
        "match_requests",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "APPROVED",
                "REJECTED",
                name="matchrequeststatus",
                create_type=False,
            ),
            server_default="PENDING",
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "possible_matches",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("target_user_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CURRENT", "LAST", "NEXT", name="possiblematchstatus", create_type=False
            ),
            server_default="CURRENT",
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "matches",
        sa.Column("rate", sa.SmallInteger(), server_default="0", nullable=True),
    )
    # op.alter_column('matches', 'status',
    #            existing_type=sa.VARCHAR(length=20),
    #            type_=sa.Enum('FOLLOWING', 'UNCOMPLETED', 'CANCELED_BY_INITIATOR', 'CANCELED_BY_TARGET', 'COMPLETED', 'SKIPPED', name='matchstatus'),
    #            existing_server_default='UNCOMPLETED',
    #            existing_nullable=True)
    op.alter_column(
        "skills",
        "weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
        existing_server_default=sa.text("'0'::smallint"),
    )
    op.alter_column(
        "user_photos",
        "photo_type",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.add_column(
        "users", sa.Column("rate", sa.SmallInteger(), server_default="0", nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("is_active", sa.Boolean(), server_default="True", nullable=False),
    )
    op.alter_column(
        "users",
        "bio",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=4096),
        existing_nullable=True,
    )
    op.drop_column("users", "rating")
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "rating",
            sa.SMALLINT(),
            server_default=sa.text("'0'::smallint"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "users",
        "bio",
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=512),
        existing_nullable=True,
    )
    op.drop_column("users", "is_active")
    op.drop_column("users", "rate")
    op.alter_column(
        "user_photos",
        "photo_type",
        existing_type=sa.String(length=20),
        type_=sa.VARCHAR(length=10),
        existing_nullable=True,
    )
    op.alter_column(
        "skills",
        "weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
        existing_server_default=sa.text("'0'::smallint"),
    )
    op.alter_column(
        "matches",
        "status",
        existing_type=sa.Enum(
            "FOLLOWING",
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
            name="matchstatus",
        ),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.drop_column("matches", "rate")
    op.drop_table("possible_matches")
    op.drop_table("match_requests")
    sa.Enum("CURRENT", "LAST", "NEXT", name="possiblematchstatus").drop(op.get_bind())
    sa.Enum("PENDING", "APPROVED", "REJECTED", name="matchrequeststatus").drop(
        op.get_bind()
    )
    sa.Enum(
        "FOLLOWING",
        "UNCOMPLETED",
        "CANCELED_BY_INITIATOR",
        "CANCELED_BY_TARGET",
        "COMPLETED",
        "SKIPPED",
        name="matchstatus",
    ).drop(op.get_bind())
    # ### end Alembic commands ###
