"""remove score from possible match

Revision ID: a83a4a8b3389
Revises: 1f8e1832b25d
Create Date: 2026-01-31 08:34:12.474396

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "a83a4a8b3389"
down_revision: Union[str, Sequence[str], None] = "1f8e1832b25d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("possible_matches", "score")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "possible_matches",
        sa.Column(
            "score",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
