"""fix typo

Revision ID: bf3004f362c5
Revises: 368d5622fc6e
Create Date: 2026-03-06 16:16:09.028392

"""
from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context

# revision identifiers, used by Alembic.
revision: str = 'bf3004f362c5'
down_revision: Union[str, Sequence[str], None] = '368d5622fc6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience', sa.SmallInteger(), nullable=True))
    op.drop_column('users', 'expierence')
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get('data', None):
        data_upgrades()

def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('expierence', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'experience')
    # ### end Alembic commands ###
