"""match_algorithm_for_user

Revision ID: c2806d3c0965
Revises: 22996e9d8adb
Create Date: 2026-01-08 19:36:41.821667

"""

import os
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import context, op
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "c2806d3c0965"
down_revision: Union[str, Sequence[str], None] = "22996e9d8adb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("UNFILLED_CUU", "EVALUATION", "FILLED", name="usermatchstatus").create(
        op.get_bind()
    )
    op.create_table(
        "user_match_state",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column(
            "current_status",
            postgresql.ENUM(
                "UNFILLED_CUU",
                "EVALUATION",
                "FILLED",
                name="usermatchstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.Column(
            "next_status",
            postgresql.ENUM(
                "UNFILLED_CUU",
                "EVALUATION",
                "FILLED",
                name="usermatchstatus",
                create_type=False,
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "users",
        sa.Column(
            "count_meets_in_week", sa.Integer(), server_default="2", nullable=False
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "count_meets_in_week")
    op.drop_table("user_match_state")
    sa.Enum("UNFILLED_CUU", "EVALUATION", "FILLED", name="usermatchstatus").drop(
        op.get_bind()
    )

    # ### end Alembic commands ###
