"""update match

Revision ID: c5ef317e2938
Revises: 85ae63976f0c
Create Date: 2026-01-22 18:38:25.484151

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa

from alembic import context
import alembic_postgresql_enum

# revision identifiers, used by Alembic.
revision: str = "c5ef317e2938"
down_revision: Union[str, Sequence[str], None] = "85ae63976f0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("matches", sa.Column("video_link", sa.String(), nullable=True))
    op.sync_enum_values(
        "public",
        "usermatchstatus",
        ["UNFILLED", "EVALUATION", "FILLED"],
        [("user_match_state", "current_status"), ("user_match_state", "next_status")],
        enum_values_to_rename=[("UNFILLED_CUU", "UNFILLED")],
    )
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "usermatchstatus",
        ["UNFILLED_CUU", "EVALUATION", "FILLED"],
        [("user_match_state", "current_status"), ("user_match_state", "next_status")],
        enum_values_to_rename=[],
    )
    op.drop_column("matches", "video_link")
    # ### end Alembic commands ###
