"""Change embedding index type

Revision ID: d310f79a43ef
Revises: a83a4a8b3389
Create Date: 2026-02-10 11:55:49.980377

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

# revision identifiers, used by Alembic.
revision: str = "d310f79a43ef"
down_revision: Union[str, Sequence[str], None] = "a83a4a8b3389"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("possible_matches")
    sa.Enum("CURRENT", "LAST", "NEXT", name="possiblematchstatus").drop(op.get_bind())
    op.sync_enum_values(
        "public",
        "matchstatus",
        [
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
            "ONGOING",
        ],
        [("matches", "status")],
        enum_values_to_rename=[],
    )
    op.drop_index(
        "user_embedding_index",
        table_name="user_embeddings",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64, "dim": 768},
        postgresql_ops={"embedding": "vector_l2_ops"},
    )
    op.create_index(
        "user_embedding_index",
        "user_embeddings",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "matchstatus",
        [
            "FOLLOWING",
            "UNCOMPLETED",
            "CANCELED_BY_INITIATOR",
            "CANCELED_BY_TARGET",
            "COMPLETED",
            "SKIPPED",
            "ONGOING",
        ],
        [("matches", "status")],
        enum_values_to_rename=[],
    )
    sa.Enum("CURRENT", "LAST", "NEXT", name="possiblematchstatus").create(op.get_bind())
    op.create_table(
        "possible_matches",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("target_user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "CURRENT", "LAST", "NEXT", name="possiblematchstatus", create_type=False
            ),
            server_default=sa.text("'CURRENT'::possiblematchstatus"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
            name=op.f("possible_matches_target_user_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("possible_matches_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("possible_matches_pkey")),
    )
    # ### end Alembic commands ###
