"""add feedback

Revision ID: d5a97e9137bf
Revises: 048910357d06
Create Date: 2026-03-03 17:40:32.009089

"""

from typing import Sequence, Union

from alembic import op
import os
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import context

# revision identifiers, used by Alembic.
revision: str = "d5a97e9137bf"
down_revision: Union[str, Sequence[str], None] = "048910357d06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "match_criterias",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("common_skills", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("common_goals", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("target_ids", postgresql.ARRAY(sa.UUID()), nullable=True),
        sa.Column("cosine_distance", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_scores",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("review", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "match_snapshots",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("match_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("skills", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("goals", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("bio", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("matches", "rate")
    # ### end Alembic commands ###
    if context.get_x_argument(as_dictionary=True).get("data", None):
        data_upgrades()


def data_upgrades():
    for file in os.listdir("db/data"):
        if file.endswith(".sql"):
            with open(f"db/data/{file}", "r") as f:
                op.execute(f.read())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "matches",
        sa.Column(
            "rate",
            sa.SMALLINT(),
            server_default=sa.text("'0'::smallint"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("match_snapshots")
    op.drop_table("match_scores")
    op.drop_table("match_criterias")
    # ### end Alembic commands ###
